### PRODUCTOS

### Recuperar todos los productos
GET http://localhost:1234/products

### Recuperar un producto por id
GET http://localhost:1234/products/072fad3a-b2df-47f2-a156-43f876b7b13f

### Recuperar todos los productos por una categoria
GET http://localhost:1234/products?category=running&brand=nike

### Crear un producto con POST
POST http://localhost:1234/products/
Content-Type: application/json

{
  "name": "Nike Messi",
  "price": 120,
  "category": "running",
  "brand": "Nike",
  "image" : "http://localhost:5173/products",
  "stock": [
    {
      "size": 37,
      "quantity": 7
    }]
}
### Actualizar un producto (falta normalizar strings) 
PATCH http://localhost:1234/products/f166276b-ecc5-4065-a566-91796731cff3
Content-Type: application/json

{
  "name" : "adidas MESSi" 
}

### eliminar un producto
DELETE http://localhost:1234/products/f166276b-ecc5-4065-a566-91796731cff3

### MARCAS


### Obtener las marcas
GET http://localhost:1234/brands/

### Obtener una marca
GET http://localhost:1234/brands/5

### Borrar una marca (poner not found)
DELETE http://localhost:1234/brands/14

### Crear una marca 
POST http://localhost:1234/brands/
Content-Type: application/json

{
  "name" : "topper",
  "image" : "http://localhost:5173/"
}

### Actualizar una marca 
patch http://localhost:1234/brands/14
Content-Type: application/json

{
  "image" : "https://ik.imagekit.io/footgear/img/puma-banner.jpg"
}


### CATEGORIAS


### Obtener las categorias
GET http://localhost:1234/categories/

### Obtener una categoria
GET http://localhost:1234/categories/14

### Borrar una categoria
DELETE http://localhost:1234/categories/14

### Crear una categoria 
POST http://localhost:1234/categories/
Content-Type: application/json

{
  "name": "skateboarding", 
  "image" : "http://localhost:5173/"
}

### Actualizar una categoria 
PATCH http://localhost:1234/categories/13
Content-Type: application/json

{
  "image" : "https://ik.imagekit.io/footgear/img/puma-walking.webp"
}

### Obtener todos los stocks (verificar rendimiento)
GET http://localhost:1234/stocks/

### Obtener un stock por id
GET http://localhost:1234/stocks/4

### Crear un stock 
POST http://localhost:1234/stocks/
Content-Type: application/json

{
  "size" : 48,
  "product_id" : "072fad3a-b2df-47f2-a156-43f876b7b13f",
  "quantity" : 5
}

### Actualizar un stock 
PATCH http://localhost:1234/stocks/5
Content-Type: application/json

{
  "quantity" : 10
}

### Obtener todos los stocks de un producto
GET http://localhost:1234/stocks/product/072fad3a-b2df-47f2-a156-43f876b7b13f

### Eliminar un stock 
DELETE http://localhost:1234/stocks/274


### Obtener todos los clientes
GET http://localhost:1234/customers/

### Obtener un cliente por id
GET http://localhost:1234/customers/195b4909-d4cd-4437-b2a6-d55be212e606

### Crear un cliente
POST http://localhost:1234/customers/
Content-Type: application/json

{
  "name": "Fernando Palomo",
  "email": "fpaloma@gmail.com",
  "address": "Juan Fernando Quintero 3125",
  "phone" : "01121785466"
}

### Actualizar un cliente
PATCH http://localhost:1234/customers/6d8020e1-05c1-4811-9699-cd0dd0d8bcc8
Content-Type: application/json

{
  "name" : "Lionel Messi"
}

### Eliminar un cliente
DELETE http://localhost:1234/customers/2e66af9e-4331-432b-853d-196ec0c2c0b0


### Obtener todas las ordenes
GET http://localhost:1234/orders/

### Obtener una orden por id
GET http://localhost:1234/orders/d7db0c98-c007-4a45-a143-4561dc4c4990

### Crear una orden
POST http://localhost:1234/orders/
Content-Type: application/json

{
  "customer_id" : "a4100707-d931-4e75-9a4e-a20beae7fa10",
  "total_amount" : 300
}
### Actualizar una orden
PATCH http://localhost:1234/orders/1f783d0c-72ea-4ba4-9018-a8c1c44d592d
Content-Type: application/json

{
  "customer_id" : "e7d59e9d-bdc4-4176-8d0d-d5e097929c71",
  "status" : "delivered"
}

### Eliminar una orden
DELETE http://localhost:1234/orders/cbbe59f8-3082-41e7-97f8-06b0356f8407

### Obtener todos los order_items
GET http://localhost:1234/order_items/

### Obtener order_items con order_id
GET http://localhost:1234/order_items/order/1f783d0c-72ea-4ba4-9018-a8c1c44d592d

### Recuperar un order_item
GET http://localhost:1234/order_items/aff414b4-87f2-4abc-ad96-5b596738c59d

### Crear un order_item
POST http://localhost:1234/order_items/
Content-Type: application/json 

{
  "order_id" : "2b2f7cd4-449d-4365-924c-5028c6df7bb1",  
  "stock_id": 260 ,
  "price": 110,
  "quantity" : 1
}

### Actualizar un order_item
PATCH http://localhost:1234/order_items/aff414b4-87f2-4abc-ad96-5b596738c59d
Content-Type: application/json

{
  "price" : 220,
  "quantity" : 2
}

### Eliminar un order_item
DELETE http://localhost:1234/order_items/aff414b4-87f2-4abc-ad96-5b596738c59d

### Realizar una compra 
POST http://localhost:1234/orders/buy
Content-Type: application/json

{
  "name": "Juan Fernando Quintero",
  "email": "jfq@gmail.com",  
  "phone": "11215446",
  "address": "Enrique Fernandez 2342",
  "items": [
    {
      "stock_id" : 4,
      "price" : 120,
      "quantity" : 1
    },
    {
      "stock_id" : 5,
      "price" : 120,
      "quantity" : 1
    }
  ],
  "total_amount" : 240
}
