CREATE TABLE IF NOT EXISTS category (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL UNIQUE 
);
CREATE TABLE IF NOT EXISTS brand (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS product( 
id BINARY(16) PRIMARY KEY,
name VARCHAR(255) NOT NULL UNIQUE,
price DECIMAL(10,2) NOT NULL CHECK (price BETWEEN 50 AND 300),
image TEXT NOT NULL,
brand_id INT NOT NULL,
category_id INT NOT NULL,
FOREIGN KEY(brand_id) REFERENCES brand(id),
FOREIGN KEY(category_id) REFERENCES category(id)
);
CREATE TABLE IF NOT EXISTS stock (
id INT AUTO_INCREMENT PRIMARY KEY, 
product_id BINARY(16) NOT NULL,
size INT NOT NULL CHECK (size BETWEEN 30 AND 50),
quantity INT NOT NULL CHECK (quantity >= 0),
FOREIGN KEY(product_id) REFERENCES product(id) ON DELETE CASCADE
);
